// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Data {
    #[prost(message, repeated, tag = "1")]
    pub mail_send_event_event_list: ::prost::alloc::vec::Vec<MailSendEventEvent>,
    #[prost(message, repeated, tag = "2")]
    pub mail_v2_send_event_event_list: ::prost::alloc::vec::Vec<MailV2SendEventEvent>,
    #[prost(message, repeated, tag = "3")]
    pub mail_v2_update_event_event_list: ::prost::alloc::vec::Vec<
        MailV2UpdateEventEvent,
    >,
    #[prost(message, repeated, tag = "4")]
    pub mail_v2_read_event_event_list: ::prost::alloc::vec::Vec<MailV2ReadEventEvent>,
    #[prost(message, repeated, tag = "5")]
    pub mail_v2_update_label_event_event_list: ::prost::alloc::vec::Vec<
        MailV2UpdateLabelEventEvent,
    >,
    #[prost(message, repeated, tag = "6")]
    pub mail_account_v2_register_event_event_list: ::prost::alloc::vec::Vec<
        MailAccountV2RegisterEventEvent,
    >,
    #[prost(message, repeated, tag = "7")]
    pub mail_account_v2_update_event_event_list: ::prost::alloc::vec::Vec<
        MailAccountV2UpdateEventEvent,
    >,
    #[prost(message, repeated, tag = "8")]
    pub createmail_instruction_list: ::prost::alloc::vec::Vec<CreatemailInstruction>,
    #[prost(message, repeated, tag = "9")]
    pub updatemail_instruction_list: ::prost::alloc::vec::Vec<UpdatemailInstruction>,
    #[prost(message, repeated, tag = "10")]
    pub updatemailreadstatus_instruction_list: ::prost::alloc::vec::Vec<
        UpdatemailreadstatusInstruction,
    >,
    #[prost(message, repeated, tag = "11")]
    pub updatemaillabel_instruction_list: ::prost::alloc::vec::Vec<
        UpdatemaillabelInstruction,
    >,
    #[prost(message, repeated, tag = "12")]
    pub register_v2_instruction_list: ::prost::alloc::vec::Vec<RegisterV2Instruction>,
    #[prost(message, repeated, tag = "13")]
    pub update_account_v2_instruction_list: ::prost::alloc::vec::Vec<
        UpdateAccountV2Instruction,
    >,
    #[prost(message, repeated, tag = "14")]
    pub sendmail_instruction_list: ::prost::alloc::vec::Vec<SendmailInstruction>,
    #[prost(message, repeated, tag = "15")]
    pub register_instruction_list: ::prost::alloc::vec::Vec<RegisterInstruction>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MailSendEventEvent {
    #[prost(string, tag = "1")]
    pub trx_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub to: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MailV2SendEventEvent {
    #[prost(string, tag = "1")]
    pub trx_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub to: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub mailbox: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MailV2UpdateEventEvent {
    #[prost(string, tag = "1")]
    pub trx_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub to: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub mailbox: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub parent_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub mark_as_read: bool,
    #[prost(uint32, tag = "8")]
    pub created_at: u32,
    #[prost(string, tag = "9")]
    pub subject: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub body: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub iv: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub salt: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MailV2ReadEventEvent {
    #[prost(string, tag = "1")]
    pub trx_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub owner: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MailV2UpdateLabelEventEvent {
    #[prost(string, tag = "1")]
    pub trx_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub owner: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MailAccountV2RegisterEventEvent {
    #[prost(string, tag = "1")]
    pub trx_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub account: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MailAccountV2UpdateEventEvent {
    #[prost(string, tag = "1")]
    pub trx_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub account: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatemailInstruction {
    #[prost(string, tag = "1")]
    pub trx_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub subject: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub to: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub salt: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub iv: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub parent_id: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub acct_mail: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub acct_mail_account_v2: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub acct_authority: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub acct_system_program: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatemailInstruction {
    #[prost(string, tag = "1")]
    pub trx_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub body: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub acct_mail: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub acct_authority: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub acct_system_program: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatemailreadstatusInstruction {
    #[prost(string, tag = "1")]
    pub trx_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub acct_mail: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub acct_authority: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub acct_system_program: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatemaillabelInstruction {
    #[prost(string, tag = "1")]
    pub trx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub label: u64,
    #[prost(string, tag = "3")]
    pub acct_mail: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub acct_authority: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub acct_system_program: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterV2Instruction {
    #[prost(string, tag = "1")]
    pub trx_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub nostr_key: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub acct_mail_account_v2: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub acct_authority: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub acct_system_program: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateAccountV2Instruction {
    #[prost(string, tag = "1")]
    pub trx_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub nostr_key: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub mailbox: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub acct_mail_account_v2: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub acct_authority: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendmailInstruction {
    #[prost(string, tag = "1")]
    pub trx_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub subject: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub body: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub to: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub salt: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub iv: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub acct_mail: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub acct_authority: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub acct_system_program: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterInstruction {
    #[prost(string, tag = "1")]
    pub trx_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub nostr_key: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub acct_mail_account: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub acct_authority: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub acct_system_program: ::prost::alloc::string::String,
}
